### PR TITLE
Updated spring-boot, snakeyaml, spring-cloud-starter-bootstrap, version

### PR DESCRIPTION
**Pull request by AndreiOla**
**Changed**
Updated spring-boot, snakeyaml, spring-cloud-starter-bootstrap, version, in order to fix Vulnerabilities.

### CODE REVIEW

**Comment by AndreiOla** [comment]
Hey @tlawrie Can you also add me as a Contributor to this Fork: https://github.com/boomerang-io/flow.lib.distributed-lock?
Also please add some Reviewers to this PR, as I am not allowed.

**Comment by AndreiOla** [comment]
Hey @tlawrie Please Review this and add me as a Contributor.

**Comment by tlawrie** [comment]
Hi @AndreiOla looking for a plus one from the IBM maintainers who should be able to make the changes.

@gchickma @BenjaminRuby @timrbula

**Comment by AndreiOla** [comment]
Hey @tlawrie  @gchickma @BenjaminRuby @timrbula, please add yourself as a Reviwer and Approve this PR, so I can merge it. Also, please add me as Contributor with "write" rights, so I can add Reviewers and push changes in this Fork.

**Comment by BenjaminRuby** [comment]
Hey @AndreiOla - added @amhudson and @gchickma as reviewers for this PR. I am not too familiar with this spring library

**Review by amhudson — APPROVED** [review]

**Review by gchickma — COMMENTED** [review]
Looks good to me

**Pull request merged**
